spring:
  application:
    name: Trip Web Admin

multipart:
  enabled: true # Enable support of multi-part uploads.
  file-size-threshold: 4KB # Threshold after which files will be written to disk. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
  location: /tmp # Intermediate location of uploaded files.
  max-file-size: 5Mb # Max file size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.
  max-request-size: 50Mb # Max request size. Values can use the suffixed "MB" or "KB" to indicate a Megabyte or Kilobyte size.

upload:
  work-folder-name: /Users/zhangxd/files
  access-url: http://images.192.168.199.237.xip.io:8888
