logging:
  level:
    ROOT: INFO
    cn.zhangxd.trip.infrastructure: DEBUG

spring:
  application:
    name: Trip Service Provider
  # DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x' FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
  redis:
    database: 0
    host: 127.0.0.1
    #password: # Login password of the redis server.
    port: 6379
    timeout: 0
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数
  data:
    mongodb:
      database: trip # Database name.
      host: localhost # Mongo server host.
      port: 27017 # Mongo server port.

#  boot:
#    admin:
#      url: http://localhost:8888

api:
  taobao:
    sms:
      url: http://gw.api.taobao.com/router/rest
      key: 23393509
      secret: fbee7a46d4fa2341e0baec53c0d027ef
  hefeng:
    weather:
      url: https://api.heweather.com/x3/weather
      key: 15a3e1ddf6c84ff39025a3d5b180dd46
  google:
    map:
      key: AIzaSyAI7VcvuL29G6ApZWUYQRQuJV1-Rav7JWM
  baidu:
    map:
      key: WyGjNtedCH8jTgccE7zvRySuPVwhTGR1
  map:
    enable: baidu # baidu or google